name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: NPM Install
        working-directory: ui
        run: npm ci
          
      - name: NPM Lint
        working-directory: ui
        run: npm run lint
          
      - name: NPM Build
        working-directory: ui
        run: npm run build
          
      - uses: actions/setup-dotnet@v3

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Build
        run: dotnet build --configuration Release --no-restore

      - name: Dotnet Test
        run: dotnet test --no-restore --verbosity normal

      - name: Upload nuget packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: packages

      - name: Nuget Push
        run: |
          dotnet nuget push "*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
